<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sujit" failures="0" tests="5" name="api.test.UserTest" time="0.147" errors="1" timestamp="2024-08-25T10:51:50 IST" skipped="4">
  <testcase classname="api.test.UserTest" name="createData" time="0.146">
    <error message="Cannot invoke &quot;api.Payload.userPayload.setId(int)&quot; because &quot;this.payload&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "api.Payload.userPayload.setId(int)" because "this.payload" is null
at api.test.UserTest.createData(UserTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:644)
at org.testng.TestRunner.beforeRun(TestRunner.java:633)
at org.testng.TestRunner.run(TestRunner.java:595)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createData -->
  <system-out/>
  <testcase classname="api.test.UserTest" name="createUserTest" time="0.001">
    <skipped/>
  </testcase> <!-- createUserTest -->
  <system-out/>
  <testcase classname="api.test.UserTest" name="updateUserTest" time="0.000">
    <skipped/>
  </testcase> <!-- updateUserTest -->
  <system-out/>
  <testcase classname="api.test.UserTest" name="getUserTest" time="0.000">
    <skipped/>
  </testcase> <!-- getUserTest -->
  <system-out/>
  <testcase classname="api.test.UserTest" name="deleteUserTest" time="0.000">
    <skipped/>
  </testcase> <!-- deleteUserTest -->
  <system-out/>
</testsuite> <!-- api.test.UserTest -->
